name: Node.js CI

on:
  push:
    branches: [ '**' ]
    tags: [ '**' ]
  release:
    types: [ 'created' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
      env:
        CI: true
    - name: Install Code Coverage Dependency
      run: npm install codecov -g
    - name: Run Unit Tests
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: npm run coverage:ci
      env:
        NODE_ENV: production
    - name: Report Code Coverage
      run: codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
